fix : .env 생성 문제 해결

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -22,16 +22,17 @@ jobs:
           ${{ secrets.ENV_FILE }}
           EOF
 
-      - name: Copy .env AND docker-compose to EC2
+      - name: Copy docker-compose to EC2
         uses: appleboy/scp-action@v0.1.7
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
-          source: "docker-compose.yml,.env"
+          source: "docker-compose.yml"
           target: "/home/${{ secrets.EC2_USERNAME }}/app"
+          overwrite: true
 
-      - name: Deploy with Docker Compose
+      - name: Create .env file AND Deploy with Docker Compose
         uses: appleboy/ssh-action@v1.0.0
         with:
           host: ${{ secrets.EC2_HOST }}
@@ -39,6 +40,18 @@ jobs:
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
             cd /home/${{ secrets.EC2_USERNAME }}/app
+            
+            cat << 'EOF' > .env
+            ${{ secrets.ENV_FILE}}
+            EOF
+            
+            if [! -f .env]; then
+              echo "ERROR : .env NOT Created"
+              exit 1
+            fi
+            
+            echo ".env Created Successfully"
+            ls -la .env
             
             echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
             
